#!/usr/bin/env ruby

require 'rubygems'
require 'erb'
require 'configliere'
require 'wukong/schema'
require File.dirname(__FILE__)+'/twitter_object_paths'

Settings.use    :commandline
Settings.define :pig_opts, :default => ""
Settings.define :output,   :require => true
Settings.define :schema,   :description => "ERB template declaring load schemas"
Settings.define :maybe    #run only if output doesnt already exist
Settings.resolve!

class PigScript
  attr_accessor :name, :schema, :body

  PIG_SCRIPT_DIR = '/tmp/swineherd'
  
  #
  # template should be something like "degree_distribution.pig.erb"
  #
  def initialize template
    self.name   = File.basename(template).gsub(".erb","")
    self.schema = ERB.new(File.read(Settings.schema))
    self.body   = ERB.new(File.read(template))
  end

  def content
    [schema.result, body.result].join("\n")
  end

  def execute!
    return "Output exists, skipping..." if Settings.maybe && hdfs_path_exists?(Settings.output)
    FileUtils.mkdir_p(PIG_SCRIPT_DIR)
    script_path = File.join(PIG_SCRIPT_DIR, name)
    File.open(script_path, 'w') do |f|
      f << content
    end
    remove_hdfs_path Settings.output
    system %Q{pig #{Settings.pig_opts} #{script_path}}
  end

  def hdfs_path_exists? path
    system %Q{hadoop fs -test -e #{path}}
  end

  def remove_hdfs_path path
    system %Q{hdp-rm -r #{path}}
  end

end

script = PigScript.new('examples/degree_distribution.pig.erb')
script.execute!
